name: Tools
version: '1.7.0-SNAPSHOT'
main: pl.lokos.tools.basic.ToolsPlugin
api-version: '26.3'
description: Modularne narzedzia serwera z asynchronicznym MySQL
author: LokosPL
website: https://github.com/LokosPL/Tools
